### ISSUE TITLE
Enabling a search engine in preferences disables it

### ISSUE THREAD

**Issue by programmeruser2** [privau/searxng#11]
Hi,

Firstly, thanks for hosting this instance, it's the fastest and most reliable instance I've found.

For some reason though when I enable a engine on the preferences page it ends up actually disabling it. And when I enable something it ends up disabling it. Is this intended behavior that's undocumented, or is this a bug?

**Comment by vojkovic** [comment]
Thanks for your issue,

I noticed this weird behavior yesterday as well, this is definitely a bug, I'll try to fix this today.

**Comment by vojkovic** [comment]
Just had to update the CSS. Should be fixed in https://github.com/privau/searxng/commit/c1a9f3d5fa6381503cb609ec9864923d9420f6bf

Closing.
