### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by Voidwyrm** [privau/searxng#15]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/privau/searxng
Branch: main
Version: 2023.6.30+8e8d8dab

**How did you install SearXNG?**
N/A
**What happened?**
DuckDuckGo gives the error message "Suspended: access denied"

**How To Reproduce**
Search on priv.au and open "Messages from the search engines"

**Expected behavior**
DuckDuckGo returns search results rather than an error message

**Screenshots & Logs**
![Screenshot 2023-07-01 223214](https://github.com/privau/searxng/assets/64708479/5a2527d3-51fd-42dd-806b-26eb549e0328)

**Additional context**
This happens on both Firefox and Chrome

**Technical report**

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 30
  * Parameters: `(None, None, 'duckduckgo.com')`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = get(query_url, headers=headers)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 15
  * Parameters: `(None, None, None)`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = get(query_url, headers=headers)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ConnectTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadError
  * Percentage: 0
  * Parameters: `(None, None, 'lite.duckduckgo.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadError
  * Percentage: 0
  * Parameters: `(None, None, 'duckduckgo.com')`
  * File name: `searx/engines/duckduckgo.py:98`
  * Function: `get_vqd`
  * Code: `res = get(query_url, headers=headers)`

**Comment by vojkovic** [comment]
It seems that DuckDuckGo is rate limiting my instance. [I've disabled DuckDuckGo as a default search engine](https://github.com/privau/searxng/commit/43fb71726c5d6bb54a6d2d4e812013b2ef854a88), hopefully it will be removed from the rate limit soon.
