### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by Voidwyrm** [privau/searxng#16]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/privau/searxng
Branch: main
Version: 2023.7.1+5720844f

**How did you install SearXNG?**
N/A
**What happened?**
DuckDuckGo gives the error message "Suspended: access denied"

**How To Reproduce**
Search on priv.au and open "Messages from the search engines"

**Expected behavior**
DuckDuckGo returns search results rather than an error message

**Screenshots & Logs**
![image](https://github.com/privau/searxng/assets/64708479/cc0dcba8-cba5-46df-b657-ac1b708c2e9c)

**Additional context**
Happens on both Firefox and Chrome

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.InvalidURL
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'www.google.ru')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by Voidwyrm** [comment]
It's working now

**Comment by stemy2** [comment]
Not anymore.

**Comment by vojkovic** [comment]
@stemy2 Google has been very spotty recently. In the meantime, I would recommend trying another instance.
