### ISSUE TITLE
Bug: google scholar engine

### ISSUE THREAD

**Issue by boterocamilo** [privau/searxng#29]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/privau/searxng
Branch: main
Version: 2023.12.3+3829c253f

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 0
  * Parameters: `('CAPTCHA',)`
  * File name: `searx/engines/google_scholar.py:90`
  * Function: `detect_google_captcha`
  * Code: `raise SearxEngineCaptchaException()`

**Comment by vojkovic** [comment]
Looks like scholar is down for priv.au. You may have to use another instance in order to use it.
