### ISSUE TITLE
Change weight

### ISSUE THREAD

**Issue by lovfi** [privau/searxng#30]
Is it possible to change the weight of each search engine? If not, please allow editing weight and other values on the engines page in settings.

**Comment by vojkovic** [comment]
@lovfi 

This is not a feature of SearXNG. If you would like to raise a feature request with the SearXNG maintainers you can open an issue here: https://github.com/searxng/searxng/issues

Only the maintainer of a SearXNG instance is currently able to change the weights of engines. priv.au is currently using the default weights provided by the SearXNG project.

If you can point me towards some examples of poor results resulting from bad engine weights, it would be my pleasure to investigate further for you.

**Comment by vojkovic** [comment]
Closing due to https://github.com/searxng/searxng/issues/3093
