### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by privauuser** [privau/searxng#33]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/privau/searxng
Branch: main
Version: 2024.3.9+691390b44

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 5
  * Parameters: `('Too many request',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.ReadTimeout
  * Percentage: 0
  * Parameters: `(None, None, 'search.brave.com')`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by privauuser** [comment]
is this happening because i'm using vpn or custom dns?

**Comment by privauuser** [comment]
is this because i am using a vpn or custom dns?

**Comment by vojkovic** [comment]
Hi,

Thanks for your issue. Brave has temporarily blocked the European instance of priv.au. These blocks commonly occur in public instances and can often take multiple hours to resolve. However, the Singaporean instance is still unblocked. If you wish to use Brave search, use https://as.priv.au/ until Brave removes their block on the European instance.
