### ISSUE TITLE
Theme from the script different from the priv.au

### ISSUE THREAD

**Issue by IAM-GROOT1** [privau/searxng#34]
That's Priv.au on the Macchiato theme 
![image](https://github.com/privau/searxng/assets/97197027/2bab27b0-233f-4d05-b043-1f849801e7b4)

And this is after i ran the script but the Macchiato theme is just light theme and this is the only dark theme and doesn't have boxes for the search results  
![image](https://github.com/privau/searxng/assets/97197027/936775c8-166b-460b-b53d-62d76f591738)

also needed to thank you alot for doing this script to make searx look good

**Comment by vojkovic** [comment]
Hi There,

I don't understand what you are trying to do. Are you able to explain what steps have led you here? The script `update.sh` just builds the css files in src/css.

**Comment by vojkovic** [comment]
Closing due to lack of reply.
