### ISSUE TITLE
favicons issue in RTL languages

### ISSUE THREAD

**Issue by alr86** [privau/searxng#36]
![Screenshot_20240806_172627](https://github.com/user-attachments/assets/e9515cae-9e1a-468c-b4e1-4d20eafe0c24)

**Comment by vojkovic** [comment]
Thanks for reporting this - completely slipped by me. I'll begin work on a fix immediately and keep you updated.

**Comment by vojkovic** [comment]
Thanks for waiting - I've resolved this in https://github.com/privau/searxng/commit/fa58dd84d7a24d8789b45d9c4bfe4028a5b6454c.

![image](https://github.com/user-attachments/assets/e72b6929-18c7-4202-b985-41589d323dbf)

@alr86 If you don't mind - as a native RTL speaker, can you provide some input on https://github.com/searxng/searxng/issues/3724#issuecomment-2282176040
