### ISSUE TITLE
Firefox: Strange behaviour of search suggestions

### ISSUE THREAD

**Issue by DokterKaj** [privau/searxng#39]
When typing in the URL bar, search suggestions usually aren't shown. However, if you have a Search bar in your toolbar and you type something there then switch to the URL bar, search suggestions will be shown temporarily, then stop being shown after roughly a minute of not typing anything.

Can it be made so that search suggestions always show?

**Comment by vojkovic** [comment]
Fixed in https://github.com/privau/searxng/commit/a750d1651fc98240429209a668350592d732f7f0.

You will need to remove and re-add priv.au as your default search engine in Firefox.

Let me know if there's anything else I can do for you.
